name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  frontend:
    name: Frontend Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js  # Установка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Указываем версию Node.js

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build application
        run: |
          cd frontend
          npm run build

  backend:
    name: Backend Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code  # Клонирование репозитория
        uses: actions/checkout@v3

      - name: Set up Python  # Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
